# Generated by Django 5.2.5 on 2025-08-15 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=12)),
                ('sobrenome', models.CharField(max_length=20)),
                ('cpf', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11)])),
                ('cnpj', models.IntegerField(validators=[django.core.validators.MaxValueValidator(14)])),
                ('email', models.EmailField(max_length=50)),
                ('senha', models.CharField(validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('cliente', 'Cliente'), ('lojista', 'Lojista')], max_length=7)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.usuario')),
            ],
        ),
    ]
