# Generated by Django 5.2.5 on 2025-08-15 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('lojista', 'Lojista')], default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carteira',
            name='tipo_usuario',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cnpj',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
