# Generated by Django 5.2.5 on 2025-08-15 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0002_usuario_tipo_alter_carteira_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cnpj',
            field=models.IntegerField(default=None, unique=True, validators=[django.core.validators.MaxLengthValidator(14)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(default=None, unique=True, validators=[django.core.validators.MaxLengthValidator(11)]),
        ),
    ]
