# Generated by Django 5.2.5 on 2025-08-15 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_alter_usuario_cnpj_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
