# Generated by Django 5.2.5 on 2025-08-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_alter_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cnpj',
            field=models.IntegerField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(default=None, max_length=11, null=True, unique=True),
        ),
    ]
