# Generated by Django 5.2.5 on 2025-08-15 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0005_alter_usuario_cnpj_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cnpj',
            field=models.IntegerField(default=None, max_length=14, null=True, unique=True),
        ),
    ]
