# Generated by Django 5.2.5 on 2025-08-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0007_alter_usuario_cnpj_alter_usuario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cnpj',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
