# Generated by Django 5.2.5 on 2025-08-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0010_user_alter_carteira_usuario_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('lojista', 'Lojista')], default=2, max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='sobrenome'),
        ),
    ]
