# Generated by Django 5.2.5 on 2025-08-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0011_user_tipo_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagador', models.CharField()),
                ('recebedor', models.CharField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('data_transferencia', models.DateField(auto_now_add=True)),
                ('identificador', models.CharField(max_length=128)),
            ],
        ),
    ]
