# Generated by Django 5.2.5 on 2025-08-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0012_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.user'),
        ),
    ]
