# Generated by Django 5.2.5 on 2025-08-16 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0013_alter_transfer_pagador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='pagador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagador', to='banco.user'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='recebedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebedor', to='banco.user'),
        ),
    ]
