# Generated by Django 5.2.5 on 2025-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0014_alter_transfer_pagador_alter_transfer_recebedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='data_transferencia',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
